ALTER TABLE users
MODIFY updated_at DATE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users
MODIFY created_at DATE DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE post
MODIFY updated_at DATE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE post
MODIFY created_at DATE DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE comments
MODIFY updated_at DATE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE comments
MODIFY created_at DATE DEFAULT CURRENT_TIMESTAMP;
