ALTER TABLE users
MODIFY updated_at DATE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users
MODIFY created_at DATE DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE post
MODIFY updated_at DATE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE post
MODIFY created_at DATE DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE comments
MODIFY updated_at DATE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE comments
MODIFY created_at DATE DEFAULT CURRENT_TIMESTAMP;


CREATE OR REPLACE TRIGGER users_before_update
BEFORE UPDATE ON users
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;

CREATE OR REPLACE TRIGGER post_before_update
BEFORE UPDATE ON post
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;

CREATE OR REPLACE TRIGGER comments_before_update
BEFORE UPDATE ON comments
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;


